In [11]:
#load the lib check its version
import numpy as np
np.__version__

'2.0.2'

In [25]:
# create a list comprising number from 0 to 9
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

##### Q : converting integers to string - this style of handling lists is known as list comprehension.
##### List comprehension offers a versatile way to handle list manipulations tasks easily. We'll learn about them in future tutorials. Here's an example.

In [8]:
[str(c) for c in l ]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
[type(item) for item in l]

[int, int, int, int, int, int, int, int, int, int]

## Creating Arrays


> __NOTE__ : Numpy arrays are homogeneous in nature, i.e., they comprise one data type (integer, float, double, etc.) unlike lists.

In [31]:
# Create arrays array of zeros
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
#creating a 3 row x 5 column matrix
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
#creating a matrix with a predefined value
np.full((3,5),12.3)

array([[12.3, 12.3, 12.3, 12.3, 12.3],
       [12.3, 12.3, 12.3, 12.3, 12.3],
       [12.3, 12.3, 12.3, 12.3, 12.3]])

In [38]:
#create an array with set sequence
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
#create an array of even space between the given range of values
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [45]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

array([[-1.07644331, -0.04641714,  0.67087262],
       [-1.42445439, -0.04787663,  1.30990019],
       [-0.00684358, -0.10667822, -0.04527627]])

In [50]:
#create an identity matrix 3X3
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [55]:
#set a random seed
np.random.seed(0)
x1 = np.random.randint(10, size=6) #one dimension
print("x1 ndim:", x1.ndim)
print("x1 shape:", x1.shape)
print("x3 size: ", x1.size)
x2 = np.random.randint(10, size=(3,4)) #two dimension
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x3 size: ", x2.size)

x3 = np.random.randint(10, size=(3,4,5)) #three dimension

print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x1 ndim: 1
x1 shape: (6,)
x3 size:  6
x2 ndim: 2
x2 shape: (3, 4)
x3 size:  12
x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


## Array Indexing
> __NOTE__ : The important thing to remember is that indexing in python starts at zero.

In [57]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1


array([1, 2, 3, 4, 5, 6])

In [59]:
#assess value to index zero
print(x1[0])

1


In [67]:
#assess fifth value
print(x1[4])

5


In [61]:
#get the second last value and last
print(x1[-1])
print(x1[-2])

6
5


In [62]:
#in a multidimensional array, we need to specify row and column index
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [63]:
#1st row and 2nd column value
x2[2,3]

np.int64(7)

In [65]:
#3rd row and last value from the 3rd column
x2[2,-1]

np.int64(7)

In [66]:
#replace value at 0,0 index
x2[0,0] = 13

## Array Slicing
> __NOTE__ :  Access multiple or a range of elements from an array.

In [71]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [73]:
#from start to 4th position
x[:5]

array([0, 1, 2, 3, 4])

In [74]:
#from 4th position to end
x[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
#from 4th to 6th position
x[4:7]

array([4, 5, 6])

In [76]:
#return elements at even place
x[0::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [77]:
#return elements from first position step by two
x[1::2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [80]:
#reverse the array
x[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Array Concatenation
> Many a time, we are required to combine different arrays. So, instead of typing each of their elements manually, you can use array concatenation to handle such tasks easily.